[project]
name = "vd-games"
version = "0.1.0"
description = "Пакет с играми"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
vd-games = "VD_games.scripts.VD_main:vd_games"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
